### PR TITLE
Adds a basic sanity test to run against a remote cluster

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Adds a new feature as an enhancement to existing test framework, which enables security to run integration tests against a remote cluster
* Category : Enhancement
* Why these changes are required? : To enable security to run tests with distribution build

### Related Issues:
https://github.com/opensearch-project/security/issues/1761

### Testing
Integration test

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: build.gradle [hunk 1]
```diff
@@ -232,6 +242,7 @@ dependencies {
     implementation 'jakarta.annotation:jakarta.annotation-api:1.3.5'
     implementation "org.opensearch.plugin:transport-netty4-client:${opensearch_version}"
     implementation "org.opensearch.client:opensearch-rest-high-level-client:${opensearch_version}"
+    implementation "org.opensearch:common-utils:${common_utils_version}"
```
Comment (saratvemulapalli) [inline build.gradle:245]: This is scary. Common utils was defined to abstract out security implementation for other plugins.

I understand this is for testing only. 
Lets take it as a test dependency instead of regular dependency? 
Take a look at AD[1] for examples.

[1] https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/build.gradle#L680

File: src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    }
+
+    @Override
+    protected Settings restAdminSettings(){
+
+        return Settings
+                .builder()
+                .put("http.port", 9200)
+                .put(OPENSEARCH_SECURITY_SSL_HTTP_ENABLED, isHttps())
+                .put(OPENSEARCH_SECURITY_SSL_HTTP_PEMCERT_FILEPATH, CERT_FILE_DIRECTORY + "esnode.pem")
```
Comment (saratvemulapalli) [inline src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java:79]: Super tiny nit:
```suggestion
                .put(OPENSEARCH_SECURITY_SSL_HTTP_PEMCERT_FILEPATH, CERT_FILE_DIRECTORY + "opensearch-node.pem")
```

File: src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+                .put("plugins.security.ssl.http.pemkey_filepath", CERT_FILE_DIRECTORY + "esnode-key.pem")
```
Comment (saratvemulapalli) [inline src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java:80]: Same here.

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+public class SingleClusterSanityIT extends SecurityRestTestCase {
+
+    private static final String SECURITY_PLUGIN_NAME = "opensearch-security";
+
+    @Test
+    public void testSecurityPluginInstallation() throws Exception {
+        verifyPluginInstallationOnAllNodes();
+    }
+
+    private void verifyPluginInstallationOnAllNodes() throws Exception {
```
Comment (saratvemulapalli) [inline src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java:51]: This is nice start. 
Do you plan on writing/migrating tests which verify security plugin functionality?

**Review by saratvemulapalli — CHANGES_REQUESTED** [review]
Overall the changes are good. Lets take a test dependency on common-utils instead.

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java (hunk 4 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java:51]: yes...that is next step in the evolution of this testing process.

File: build.gradle (hunk 1 above)
Comment (DarshitChanpura) [reply build.gradle]: done

File: src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java (hunk 3 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java]: done

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java (hunk 4 above)
Comment (saratvemulapalli) [reply src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java:51]: Nice, do you have a follow up issue which takes care of it?

File: scripts/integtest.sh [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+
+if [ -z "$CLUSTER_NAME" ]
+then
+  CLUSTER_NAME="docker-cluster"
+fi
+
+USERNAME=`echo $CREDENTIAL | awk -F ':' '{print $1}'`
+PASSWORD=`echo $CREDENTIAL | awk -F ':' '{print $2}'`
+
+./gradlew integTestRemote -Dtests.rest.cluster="$BIND_ADDRESS:$BIND_PORT" -Dtests.cluster="$BIND_ADDRESS:$BIND_PORT" -Dsecurity_enabled=$SECURITY_ENABLED -Dtests.clustername=$CLUSTER_NAME -Dhttps=true -Duser=$USERNAME -Dpassword=$PASSWORD
```
Comment (saratvemulapalli) [inline scripts/integtest.sh:102]: Same here, add common-utils version as a property. 
Also check if opensearch build systems can send out common-utils version.

**Review by saratvemulapalli — DISMISSED** [review]
Overall the changes look good to me. 

Dropped a tiny comment.

File: README.md [hunk 6]
```diff
@@ -72,6 +72,16 @@ Run all tests:
 ./gradlew clean test
 ```
 
+Run tests against local cluster:
+```bash
+./gradlew integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=docker-cluster -Dsecurity=true -Dhttps=true -Duser=admin -Dpassword=admin
```
[the remark this answers is not in the document]
Comment (DarshitChanpura) [reply README.md:77]: Should we make it a requirement to pass the common-utils version every-time this script is run? or should we set a default value in case it is not passed?

File: scripts/integtest.sh (hunk 5 above)
Comment (DarshitChanpura) [reply scripts/integtest.sh:102]: It isn't part of [version.properties](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties). Should we add it there? I'm not sure about other ways it can be passed. I looked around but couldn't find any reference

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java (hunk 4 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java:51]: Yes we track it in this parent issue: https://github.com/opensearch-project/security/issues/1761

File: README.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (peternied) [reply README.md:77]: @saratvemulapalli Why do we need the common-utils version?  AFAIK the security plugin does not depend on common utils - is there some runtime dependency that is getting pulled in for the tests?

[the remark this answers is not in the document]
Comment (saratvemulapalli) [reply README.md:77]: @peternied take a look at: https://github.com/opensearch-project/security/pull/1958#discussion_r927031156

File: src/test/java/org/opensearch/bootstrap/JarHell.java [hunk 7]
```diff
@@ -0,0 +1,51 @@
+/*
```
Comment (peternied) [inline src/test/java/org/opensearch/bootstrap/JarHell.java:1]: Are these the correct license headers?

File: src/test/resources/sanity-tests/opensearch-node-key.pem [hunk 8]
```diff
@@ -0,0 +1,28 @@
+-----BEGIN PRIVATE KEY-----
```
Comment (peternied) [inline src/test/resources/sanity-tests/opensearch-node-key.pem:1]: Why do we need new certs?

File: build.gradle [hunk 9]
```diff
@@ -330,6 +340,7 @@ dependencies {
     testImplementation 'org.springframework:spring-beans:5.3.20'
     testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
     testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
+    testImplementation "org.opensearch:common-utils:${common_utils_version}"
```
Comment (peternied) [inline build.gradle:343]: What happens if common utils isn't available as we are attempting to create a fresh release?

File: README.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (DarshitChanpura) [reply README.md:77]: Following other plugins using the common Config constants, I added this as dependency in build.gradle to be able to use it throughout our plugin. But if it is becoming too complex to use it, I can replace it with the variable names and remove the dependency completely. Suggestions?

File: src/test/java/org/opensearch/bootstrap/JarHell.java (hunk 7 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/bootstrap/JarHell.java:1]: hmm..they aren't.. fixed them

File: src/test/resources/sanity-tests/opensearch-node-key.pem (hunk 8 above)
Comment (DarshitChanpura) [reply src/test/resources/sanity-tests/opensearch-node-key.pem:1]: these aren't new certs..these are generated by `install_demo_configuration.sh` script and I re-used them by placing them here. We need this, for the tests to be able to connect to the cluster.

File: build.gradle (hunk 9 above)
Comment (DarshitChanpura) [reply build.gradle:343]: We have two options here: 
1. Remove the common-utils dependency
2. Hard-code the version number that we know is always going to be available. 
I've asked similar question here: https://github.com/opensearch-project/security/pull/1958#discussion_r929130618

File: src/test/resources/sanity-tests/opensearch-node-key.pem (hunk 8 above)
Comment (peternied) [reply src/test/resources/sanity-tests/opensearch-node-key.pem:1]: Instead of copying the files can we load the certs from the path they are stored?

**Comment by DarshitChanpura** [comment]
> Can we add a CI task to run these tests on pull requests to be sure these are operational?

Done. Added it as a task to `plugin_install` CI check

File: src/test/resources/sanity-tests/opensearch-node-key.pem (hunk 8 above)
Comment (DarshitChanpura) [reply src/test/resources/sanity-tests/opensearch-node-key.pem:1]: As of now they are hard-coded in the install script and get generated when the install script is run. Only other place they are stored is in bwc-test subproject. I didn't load it from that path as it is a separate sub-project.

**Comment by DarshitChanpura** [comment]
<details>
<summary>The CI checks are failing after incrementing main to version 2.2.0.0 because it is now expecting to find common-utils with version 2.2.0.0</summary>

```
Execution failed for task ':compileTestJava'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not resolve org.opensearch:common-utils:2.2.0.0.
     Required by:
         project :
      > Could not resolve org.opensearch:common-utils:2.2.0.0.
         > Could not get resource 'https://d1nvenhzbhpy0q.cloudfront.net/snapshots/lucene/org/opensearch/common-utils/2.2.0.0/common-utils-2.2.0.0.pom'.
            > Could not GET 'https://d1nvenhzbhpy0q.cloudfront.net/snapshots/lucene/org/opensearch/common-utils/2.2.0.0/common-utils-2.2.0.0.pom'. Received status code 403 from server: Forbidden
```
</details>

Should we remove the dependency on common-utils completely as we are only using it to refer to 4 constants?

**Comment by peternied** [comment]
> hard-code the common-utils version in build.gradle 

I think this is the easiest way to keep moving forward, but please create a bug in common-utils to track this.  It seems like the dependencies we've taken on should be inside of OpenSearch's core repo

File: build.gradle [hunk 10]
```diff
@@ -21,7 +21,9 @@ buildscript {
         version_tokens = opensearch_version.tokenize('-')
         opensearch_build = version_tokens[0] + '.0'
 
-        common_utils_version = System.getProperty("common_utils.version", opensearch_build)
+        // TODO: decide whether to leave this property hardcoded or get it dynamically from core
```
Comment (peternied) [inline build.gradle:24]: Replace this comment with an issue to track this

Comment (DarshitChanpura) [reply build.gradle:24]: yep

**Comment by DarshitChanpura** [comment]
Here is the tracking issue in common-utils repository: https://github.com/opensearch-project/common-utils/issues/205

**Comment by DarshitChanpura** [comment]
> Here is the tracking issue in common-utils repository: [opensearch-project/common-utils#205](https://github.com/opensearch-project/common-utils/issues/205)

Following [the comment](https://github.com/opensearch-project/common-utils/issues/205#issuecomment-1195967728) in the tracking issue, hard-coded reference to `common-utils` will need to be updated to fetch dynamically once it publishes the latest version.

File: src/test/java/org/opensearch/bootstrap/JarHell.java (hunk 7 above)
Comment (peternied) [reply src/test/java/org/opensearch/bootstrap/JarHell.java:1]: Note; I don't see a change in the headers yet

**Comment by DarshitChanpura** [comment]
Local debugging of failure of CI check `bwc-test` fails with `java.lang.NoSuchMethodError: 'org.gradle.internal.resources.ResourceLock org.gradle.internal.resources.SharedResource.getResourceLock(int)`

This error occurs after upgrading gradle to 7.5 and is worked on in the core and a fix has been addressed [here](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java#L136)

**Comment by peternied** [comment]
@DarshitChanpura Anything you need help with to get this ready for merging?

**Comment by DarshitChanpura** [comment]
CI run fails with : 
```
Execution failed for task ':securityBwcCluster#oldVersionClusterTask1'.
> No tests found for given includes: [**/*$*.class, **/*Test*](exclude rules)
```
 but local fails with:
```
2022-08-01T12:48:34.984-0400 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':securityBwcCluster#fullRestartClusterTask' into context took 0.0 secs.
2022-08-01T12:48:34.987-0400 [INFO] [org.gradle.internal.execution.steps.SkipEmptyWorkStep] Skipping task ':securityBwcCluster#fullRestartClusterTask' as it has no source files and no previous output files.
```

Any ideas on how to solve this?

**Comment by peternied** [comment]
> local skips bwc tests with NO SOURCE:

When you run gradle add the `--rerun-tasks` flag to force gradle to execute the task, [docs](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks).

**Comment by DarshitChanpura** [comment]
> > local skips bwc tests with NO SOURCE:
> 
> When you run gradle add the `--rerun-tasks` flag to force gradle to execute the task, [docs](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks).

added it, still the same result. I think it has something to do with the filter to exclude tests

**Comment by DarshitChanpura** [comment]
I tried to print System properties to see whether [these type](https://github.com/opensearch-project/security/blob/50a94b47da5986120f4a5cbdd03d1f9d3ccae55a/bwc-test/build.gradle#L154) of `if` condition will be successfull, turns out it isn't and hence the task isn't able to find any tests classes to test

**Comment by DarshitChanpura** [comment]
> I tried to print System properties to see whether [these type](https://github.com/opensearch-project/security/blob/50a94b47da5986120f4a5cbdd03d1f9d3ccae55a/bwc-test/build.gradle#L154) of `if` condition will be successfull, turns out it isn't and hence the task isn't able to find any tests classes to test

Seems like NO SOURCE issue is Mac build system issue, @cwperks was able to replicate it on his Ubuntu EC2 instance.

File: src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java [hunk 11]
```diff
@@ -0,0 +1,114 @@
...
+import static org.opensearch.commons.ConfigConstants.OPENSEARCH_SECURITY_SSL_HTTP_KEYSTORE_PASSWORD;
+import static org.opensearch.commons.ConfigConstants.OPENSEARCH_SECURITY_SSL_HTTP_PEMCERT_FILEPATH;
+
+/**
+ * Overrides OpenSearchRestTestCase to fit the use-case for testing
+ * against remote cluster for Security Plugin.
+ *
+ * Modify this test class as needed
+ */
+@SuppressWarnings("unchecked")
```
Comment (cwperks) [inline src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java:57]: Is this needed here?

File: src/test/java/org/opensearch/bootstrap/JarHell.java (hunk 7 above)
Comment (peternied) [reply src/test/java/org/opensearch/bootstrap/JarHell.java:1]: I still don't see any update in these headers, @DarshitChanpura please update

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java [hunk 12]
```diff
@@ -0,0 +1,60 @@
...
+
+        Map<String, Map<String, Object>> nodesInCluster = (Map<String, Map<String, Object>>) getAsMapByAdmin("_nodes").get("nodes");
+
+        for (Map<String, Object> node : nodesInCluster.values()) {
+
+            List<Map<String, Object>> plugins = (List<Map<String, Object>>) node.get("plugins");
+            Set<Object> pluginNames = plugins.stream().map(map -> map.get("name")).collect(Collectors.toSet());
+
+            Assert.assertTrue(pluginNames.contains(SECURITY_PLUGIN_NAME));
```
Comment (peternied) [inline src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java:56]: Use `assertThat` and `contains` from [hamcrest](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#contains%28E...%29) for much more readable test code and debug output

```java
assertThat(pluginNames, contains(SECURITY_PLUGIN_NAME));
```

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java [hunk 13]
```diff
@@ -0,0 +1,60 @@
...
+        }
+        Assert.assertFalse(nodesInCluster.isEmpty());
```
Comment (peternied) [inline src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java:58]: Is this needed? If so please replace with `assertThat(..., isNotEmpty());`...

**Review by peternied — CHANGES_REQUESTED** [review]

File: src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java [hunk 14]
```diff
@@ -0,0 +1,114 @@
...
+
+    @Override
+    protected Settings restAdminSettings(){
+
+        return Settings
+                .builder()
+                .put("http.port", 9200)
+                .put(OPENSEARCH_SECURITY_SSL_HTTP_ENABLED, isHttps())
+                .put(OPENSEARCH_SECURITY_SSL_HTTP_PEMCERT_FILEPATH, CERT_FILE_DIRECTORY + "opensearch-node.pem")
+                .put("plugins.security.ssl.http.pemkey_filepath", CERT_FILE_DIRECTORY + "opensearch-node-key.pem")
```
Comment (cwperks) [inline src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java:76]: Should we consider adding this key and the following key to `org.opensearch.commons.ConfigConstants`?

Comment (DarshitChanpura) [reply src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java:76]: yes... although that is out of scope for this PR and can be taken into a separate PR

File: src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java (hunk 12 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java]: done

File: src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java (hunk 11 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java:57]: yes

**Review by peternied — CHANGES_REQUESTED** [review]
We still have new files that need the correct licenses headers

**Comment by DarshitChanpura** [comment]
> We still have new files that need the correct licenses headers

done

File: src/test/java/org/opensearch/bootstrap/JarHell.java (hunk 7 above)
Comment (DarshitChanpura) [reply src/test/java/org/opensearch/bootstrap/JarHell.java:1]: done

**Comment by DarshitChanpura** [comment]
CI checks need to be re-run once PR: https://github.com/opensearch-project/security/pull/1988 is merged

**Review by peternied — APPROVED** [review]

**Review by cwperks — APPROVED** [review]

**Review by davidlago — APPROVED** [review]
